site_name: CNC-CMD知识共享平台

theme:
  name: material
  features:
        - navigation.tabs  

nav:
    - 主页: 'index.md'
    - 技术文章:
        - Python: 'python.md'
        - Java: 'java.md'
    - 学习资源: 'gcr.md'
    - 项目推荐: 'project.md'
    - 学习路线: 'roadmap.md'
    - 友链: 'friend.md'
    - 关于: 'about.md'