name: ci

on:
  push: # push 触发
    paths-ignore: # 忽略README的更改，避免push后触发workflow
      - 'README.md'
    branches: # push到main或master分支时触发
      - master
      - main
  pull_request: # PR 触发
    paths-ignore:
      - 'README.md'
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test: # 构建和测试
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 设置 Python3 环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 📖 安装依赖 && 安装Mkdocs插件
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-glightbox

      - name: 🚀 构建 MKDOCS
        run: mkdocs build

  deploy: # 部署
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 设置 Git 身份
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: 安装 Python3 环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 📖 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-glightbox

      - name: 🚀 部署MKDOCS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
